config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/' => 'homes#top'
    #get '/orders/:id', to:"orders#show"
   # patch '/orders/:id', to:"orders#update"
  end


  namespace :admin do
    resources :orders
    resources :genres
    resources :items
    resources :customers
    resources :order_details
  end


  namespace :public do
    get 'orders/new'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'


  scope module: :public do
    resources :addresses
    resources :items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders
  end

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
     belongs_to :customer


    def subtotal
     item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
   #validates checked, inclusion: [true, false]
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 def full_name
   self.first_name + " " + self.last_name
 end

 def full_name_kana
   self.first_name_kana + " " + self.last_name_kana
 end

 enum is_deleted: {"退会": true, "有効": false}
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    has_one_attached :image
    
    enum is_active: {"販売中": true,"販売停止中": false}
    
    def add_tax_price
        (self.price*1.10).round
    end
    
    def with_tax_price
     (price * 1.1).floor
    end
    
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  #has_many :cart_items, through: :customer


def shipping_cost
  800
end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting_production: 1, making: 2, completion: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
   @customers = Customer.all
  end

  def show
   @customer = Customer.find(params[:id])  
  end

  def edit
   @customer = Customer.find(params[:id])  
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer.id)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end
  
   private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "paid_up"
       @order.order_details.each do |order_detail|
        order_detail.update(making_status:"waiting_production")
       end
    
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
  params.require(:order).permit(:postal_code, :address, :name,:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-9 px-5 px-sm-0 mx-auto">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
        <h5><%= @customer.full_name %>さんの会員情報編集</h5>
   
　　　　  <table class="table">
　　　　   <tbody>
　　　　    <tr>
　　　　      <td>会員ID</td>
　　　　      <td><%= @customer.id %></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>氏名</td>
　　　　      <td><%= f.text_field :first_name %></td>
　　　　      <td><%= f.text_field :last_name %></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>フリガナ</td>
　　　　      <td><%= f.text_field :first_name_kana %></td>
　　　　      <td><%= f.text_field :last_name_kana %></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>郵便番号</td>
　　　　      <td><%= f.text_field :postal_code %></td>
　　　　      <td></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>住所</td>
　　　　      <td colspan="2"><%= f.text_field :address,size: "60" %></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>電話番号</td>
　　　　      <td><%= f.text_field :telephone_number %></td>
　　　　      <td></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>メールアドレス</td>
　　　　      <td><%= f.text_field :email %></td>
　　　　      <td></td>
　　　　    </tr>
　　　　    <tr>
　　　　      <td>会員ステータス</td>
　　　　      <td>
　　　　        <%= f.radio_button :is_deleted, '有効' %>
                <%= f.label :is_deleted, '有効', value: 1 %>
                <%= f.radio_button :is_deleted, '退会' %>
                <%= f.label :is_deleted, '退会', value: 0 %>
             </td>
             <td></td>
　　　　    </tr>
　　　　   </tbody>
　　　　  </table>
　　　　  
          <div class="center-block">
            <%= f.submit "変更を保存",class:"btn btn-success" %>
          </div>
        <% end %>
    </div>
  </div>
</div>
  
       

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h4>会員一覧</h4>
     <table class="table table-hover table-inverse">
    　 <thead>
        <tr class="table-secondary">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
        <% @customers.each do |customer| %>
         <tr>
           <td>
            <%= customer.id %>
           </td>
           <td>
            <%= link_to customer.full_name,admin_customer_path(customer.id) %>
           </td>
           <td>
            <%= customer.email %>
           </td>
           <td>
            <%= customer.is_deleted  %>
           </td>
         </tr>
        <%end%>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-9 px-5 px-sm-0 mx-auto">
             <h3><%= @customer.full_name %>さんの会員詳細</h3>
              <table class="table">
                <tbody>
                    <tr>
                        <td>会員ID</td>
                        <td><%= @customer.id %></td>
                　　</tr>
    　               <tr>
    　                   <td>氏名</td>
    　                   <td><%= @customer.full_name %></td>
    　               </tr>
    　               <tr>
    　                   <td>フリガナ</td>
    　                   <td><%= @customer.full_name_kana %></td>
    　               </tr>
    　               <tr>
    　                   <td>郵便番号</td>
　　                    <td><%= @customer.postal_code %></td>
    　               </tr>
    　               <tr>
    　                   <td>住所</td>
    　                   <td><%= @customer.address %> </td>
    　              </tr>
                    <tr>
    　                   <td>電話番号</td>
    　                   <td><%= @customer.telephone_number %> </td>
    　               </tr>
    　               
                    <tr>
    　                   <td>メールアドレス</td>
    　                   <td><%= @customer.email %> </td>
    　               </tr>
    　                <tr>
    　                   <td>会員ステータス</td>
    　                   <td><%= @customer.is_deleted %> </td>
    　               </tr>
                </tbody>
            </table>
            <%=link_to edit_admin_customer_path(@customer), class:"btn btn-sm btn-success" do %>編集する
            <% end %>
         </div>
     </div>
 </div>