config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/' => 'homes#top'
    #get '/orders/:id', to:"orders#show"
   # patch '/orders/:id', to:"orders#update"
  end


  namespace :admin do
    resources :orders
    resources :genres
    resources :items
    resources :customers
    resources :order_details
  end


  namespace :public do
    get 'orders/new'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'


  scope module: :public do
    resources :addresses
    resources :items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders
  end

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
     belongs_to :customer


    def subtotal
     item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
   #validates checked, inclusion: [true, false]
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 def full_name
   self.first_name + " " + self.last_name
 end

 def full_name_kana
   self.first_name_kana + " " + self.last_name_kana
 end

 enum is_deleted: {"退会": true, "有効": false}
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    has_one_attached :image
    
    enum is_active: {"販売中": true,"販売停止中": false}
    
    def add_tax_price
        (self.price*1.10).round
    end
    
    def with_tax_price
     (price * 1.1).floor
    end
    
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  #has_many :cart_items, through: :customer


def shipping_cost
  800
end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting_production: 1, making: 2, completion: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end
  
   private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "paid_up"
       @order.order_details.each do |order_detail|
        order_detail.update(making_status:"waiting_production")
       end
    
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
  params.require(:order).permit(:postal_code, :address, :name,:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
  <div class = "container">
  <div class = "row">
    <div class = "col-7">
       <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <h5>ジャンル編集</h5> 
         <div class = "form-group">
          <table class = "table">
           <tr>
            <th><label for="name">ジャンル名</label></th>
            <th><%= f.text_field :name %></th>
            <th><%= f.submit "変更を保存",class:"btn btn-success" %></th>
           </tr>
          </table>
         </div>
         <%end%>
     </div>
    </div>
   </div>

app/views/admin/genres/index.html.erb
<div class = "container">
  <div class = "row">
      <%= form_with model: @genre, url: admin_genres_path  do |f| %>
         <h5>ジャンル一覧・追加</h5> 
          <div class = "form-group">
           <table class="table">
            <thead>
             <tr>
              <th> <label for="name">ジャンル名</label></th>
              <th><%= f.text_field :name, :placeholder =>"ジャンル名" %></th>
              <th> <%= f.submit "新規登録",class:"btn btn-success" %></th>
             </tr>
            </thead>
           </table>
          </div>
       <%end%>
  </div>
</div>
       
 <div class = "container">
  <div class = "row">
    <div class = "col-4">     
        <table class="table">
         <thead>
          <tr class="table-secondary">
           <th></th>
           <th>ジャンル</th>
           <th></th>
          </tr>
         </thead> 
         <tbody>
          <% @genres.each do |genre| %>
           <tr>
            <td><%= genre.name %></td>
            <td></td>
            <td><%=link_to edit_admin_genre_path(genre), class:"btn btn-sm btn-success" do %>編集する</td>
            <%end%>
           </tr>
          <%end%>
         </tbody>
       </table>
   </div>
  </div>
 </div>
    

         
    

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 px-sm-0 mx-auto">
    <h4>注文履歴一覧</h4>
     <table class="table table-hover table-inverse">
    　 <thead>
        <tr class="table-secondary">
          <th>購入日時</th>
          <th>購入者 </th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
        <% @orders.each do |order| %>
          <tr>
           <td>
            <%= link_to order[:created_at].strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order) %>
           </td>
            <td>
            <%= order.customer.full_name %>
            </td>
            <td>
            <%= order.order_details.sum(:amount) %>
            </td>
            <td>
            <%= order.status_i18n %>
            </td>
           </tr>
          </thead>
           <%end%>
        </table>
        </div>
      </div>
    </div>

app/views/admin/items/edit.html.erb
<div class = "container">
     <div class = "row">
         <div class = "col-3">
             <h4>商品編集</h4>
         </div>
     </div>
 </div>

 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<!-- form_withにオプション追記 -->
　　　　<%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
　　　　  <div class="form-group">
            <label for="item_name">商品画像</label>
　　　　  　<%= f.file_field :image,class:"form-control-file item_image", id:"item_image", accept:"image/*" %>
　　　　  </div>

          <div class="form-group">
            <label for="item_name">商品名　</label>
            <%= f.text_field :name %>
          </div>

  　　      <div class="form-group">
             <label for="item_introduction">商品説明</label>
             <%= f.text_area :introduction %>
          </div>

          <div class="form-group">
             <label for="item_genre_id">ジャンル</label>
             <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: '--選択してください--'} %>
          </div>

          <div class="form-group">
             <label for="item_introduction">税抜価格</label>
             <%= f.text_field :price, :placeholder =>"1000" %>円
          </div>

          <div class="form-group">
            <%= f.label :販売ステータス %>
            <%= f.radio_button :is_active, '販売中' %>
            <%= f.label :is_active, '販売中', value: 1 %>
            <%= f.radio_button :is_active, '販売停止中' %>
            <%= f.label :is_active, '販売停止中', value: 0 %>
          </div>

          <div class="center-block">
            <%= f.submit "変更を保存",class:"btn btn-success" %>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 px-sm-0 mx-auto">
    <h4>商品一覧</h4><%= link_to "＋",new_admin_item_path,class:"btn btn-sm btn-light" %>
     <table class="table table-hover table-inverse">
    　 <thead>
        <tr class="table-secondary">
          <th>商品ID</th>
          <th>商品名 </th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
        <% @items.each_with_index do |item,i| %>
          <tr>
           <td>
            <%= i+1 %>
           </td>
            <td>
             <%= link_to item.name, admin_item_path(item.id) %>
            </td>
            <td>
             <%= item.price %>
            </td>
            <td>
             <%= item.genre.name %>
            </td>
            <td>
             <%= item.is_active %>
            </td>
           </tr>
          </thead>
           <%end%>
        </table>
        </div>
      </div>
    </div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>商品新規登録</h4>
<!-- form_withにオプション追記 -->
　　　　<%= form_with model: @item, url: '/admin/items', method: :post do |f| %>

　　　　  <div class="form-group">
            <label for="item_image">商品画像</label>
            <%= f.file_field :image, accept:"image/*" %>
          </div>

          <div class="form-group">
            <label for="item_name">商品名　</label>
            <%= f.text_field :name, :placeholder =>"商品名", size:"25" %>
          </div>

  　　      <div class="form-group">
             <label for="item_introduction">商品説明</label>
             <%= f.text_area :introduction, :placeholder =>"ここに説明文を記載します", size:"25" %>
          </div>

          <div class="form-group">
             <label for="item_genre_id">ジャンル</label>
             <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: '--選択してください--'}  %>
          </div>

          <div class="form-group">
             <label for="item_introduction">税抜価格</label>
             <%= f.text_field :price, :placeholder =>"1000", size:"25" %>円
          </div>

          <div class="form-group">
            <%= f.label :販売ステータス %>
            <%= f.radio_button :is_active, '販売中' %>
            <%= f.label :is_active, '販売中', value: 1 %>
            <%= f.radio_button :is_active, '販売停止中' %>
            <%= f.label :is_active, '販売停止中', value: 0 %>
          </div>

          <div class="center-block">
            <%= f.submit "新規登録",class:"btn btn-success" %>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
 <div class = "container">
     <div class = "row">
         <div class = "col-lg-4">
             <h4>商品詳細</h4>
             <%= image_tag @item.get_image(300,300) %>
         </div>
       <div class="col-lg-8">
         <table class="table">
          <tbody>
           <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
    　      </tr>
    　      <tr>
    　       <td>商品説明</td>
    　      <td><%= @item.introduction %></td>
    　     </tr>
    　      <tr>
    　       <td>ジャンル</td>
    　       <td><%= @item.genre.name %></td>
    　     </tr>
    　      <tr>
    　       <td>税込価格
    　         （税抜価格）</td>
    　       <td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
    　     </tr>
    　      <tr>
    　        <td>販売ステータス</td>
    　        <td><%= @item.is_active %> </td>
        　</tr>
         </tbody>
         </table>
        <%=link_to edit_admin_item_path(@item.id), class:"btn btn-sm btn-success" do %>
        編集する
        <%end%>
       </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 px-5 px-sm-0 mx-auto">
      <h4>注文履歴詳細</h4>
     　<table class="table">
          <tr>
           <td><strong>購入者</strong></td>
            <td><%= @order.customer.full_name %></td>
          </tr>
          <tr>
            <td><strong>注文日</strong></td>
            <td><%= @order[:created_at].strftime("%Y/%m/%d") %></td>
          </tr>
          <tr>
            <td><strong>配送先</strong></td>
            <td>〒<%= @order.postal_code %>
                  <%= @order.address %>
             　  　<%= @order.name %></td>
          </tr>
          <tr>
            <td><strong>支払方法</strong></td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td><strong>注文ステータス</strong></td>
             <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
            <td><%= f.select :status, Order.statuses_i18n.invert %>
                <%= f.submit "更新", class:"btn btn-sm btn-success" %></td>
            <% end %>
           </tr>
          </thead>
         </table>
      </div>
     </div>
     <div class = "row">
      <div class = "col-md-9">
       <table class="table table-hover table-inverse">
    　  <thead>
         <tr class="table-secondary">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
         </tr>
        </thead>
         <% @order.order_details.each do |order_detail| %>
         <tr>
           <td>
            <%= order_detail.item.name %>
           </td>
           <td>
            <%= order_detail.item.with_tax_price %>
           </td>
           <td>
            <%= order_detail.amount %>
           </td>
           <td>
            <%= order_detail.item.with_tax_price*order_detail.amount %>
           </td>
           <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
            <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                <%= f.submit "更新", class:"btn btn-sm btn-success" %></td>
            <% end %>
         </tr>
         <% end %>
       </table>
      </div>
      <div class = "col-md-3">
        <table class="table">
          <tr>
           <td><strong>商品合計</strong></td>
           <td><%= @order.total_payment-@order.shipping_cost %>円</td>
          </tr>
          <tr>
           <td><strong>送料</strong></td>
           <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
           <td><strong>請求金額合計</strong></td>
           <td><strong><%= @order.total_payment %>円</strong></td>
          </tr>
        </table>
      </div>
     </div>
</div>