config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/' => 'homes#top'
    #get '/orders/:id', to:"orders#show"
   # patch '/orders/:id', to:"orders#update"
  end


  namespace :admin do
    resources :orders
    resources :genres
    resources :items
    resources :customers
    resources :order_details
  end


  namespace :public do
    get 'orders/new'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
  end
  devise_for :admin,skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords],controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: "public/homes#top"
  get '/about' => 'public/homes#about'


  scope module: :public do
    resources :addresses
    resources :items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders
  end

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/withdraw' => 'public/customers#withdraw'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :item
     belongs_to :customer


    def subtotal
     item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
   #validates checked, inclusion: [true, false]
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 def full_name
   self.first_name + " " + self.last_name
 end

 def full_name_kana
   self.first_name_kana + " " + self.last_name_kana
 end

 enum is_deleted: {"退会": true, "有効": false}
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items
    has_many :order_details
    
    has_one_attached :image
    
    enum is_active: {"販売中": true,"販売停止中": false}
    
    def add_tax_price
        (self.price*1.10).round
    end
    
    def with_tax_price
     (price * 1.1).floor
    end
    
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  #has_many :cart_items, through: :customer


def shipping_cost
  800
end

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting_production: 1, making: 2, completion: 3}
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
       <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>LOGO</span>
          </a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            　<% if customer_signed_in? %>
               <li class="nav-item">
                 <%= link_to "マイページ", customers_my_page_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "商品一覧", items_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "カート", cart_items_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-sm btn-light" %>
               </li>
               <% elsif admin_signed_in? %>
               <li class="nav-item">
                 <%= link_to "商品一覧", admin_items_path, class:"btn btn-sm btn-light" %>
               </li>
                <li class="nav-item">
                 <%= link_to "会員一覧", admin_customers_path, class:"btn btn-sm btn-light" %>
               </li>
                <li class="nav-item">
                 <%= link_to "注文履歴一覧", admin_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-sm btn-light" %>
               </li>
               <% else %>
               <li class="nav-item">
                 <%= link_to "About", about_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "商品一覧", items_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-sm btn-light" %>
               </li>
               <li class="nav-item">
                 <%= link_to "ログイン", new_customer_session_path, class:"btn btn-sm btn-light" %>
              </li>
             <%end%>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  <main class="mb-auto">
  <% flash.each do |message_type, message| %>
   <%=content_tag(:div, message,class:message_type)%>
  <%end%>
    <%= yield %>
  </main>
</html>

app/views/publics/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>